const patient = {
  "resourceType": "Patient",
  "id": "58b3663e3425def0f0f6960a",
  "text": {
    "status": "generated",
    "div": "<div>Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>. Version identifier: abb19fb6343d94061d3cec2142ac2e3d332ac45e</div>"
  },
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v3/Race",
            "code": "2106-3",
            "display": "White"
          }
        ],
        "text": "race"
      }
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/us-core-ethnicity",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v3/Ethnicity",
            "code": "2186-5",
            "display": "Nonhispanic"
          }
        ],
        "text": "ethnicity"
      }
    },
    {
      "url": "http://standardhealthrecord.org/fhir/extensions/placeOfBirth",
      "valueAddress": {
        "city": "Boston",
        "state": "MA"
      }
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
      "valueString": "Destiney812 Conn2"
    },
    {
      "url": "http://standardhealthrecord.org/fhir/extensions/fathersName",
      "valueString": "Tomasa507 Doyle303"
    }
  ],
  "identifier": [
    {
      "system": "https://github.com/synthetichealth/synthea",
      "value": "000081be-8df2-48b6-91bc-9b197593e2d4"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/identifier-type",
            "code": "SB"
          }
        ]
      },
      "system": "http://hl7.org/fhir/sid/us-ssn",
      "value": "999571381"
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/v2/0203",
            "code": "DL"
          }
        ]
      },
      "system": "urn:oid:2.16.840.1.113883.4.3.25",
      "value": "S99960561"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Doyle303",
      "given": [
        "Nils374"
      ],
      "prefix": [
        "Ms."
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "398-417-4032",
      "use": "home"
    }
  ],
  "gender": "female",
  "birthDate": "1971-07-25",
  "address": [
    {
      "line": [
        "37700 Nannie Island"
      ],
      "city": "Wareham",
      "state": "MA",
      "postalCode": "02571"
    }
  ],
  "maritalStatus": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/v3/MaritalStatus",
        "code": "S"
      }
    ]
  },
  "multipleBirthBoolean": false
}

export default patient;
